@IssueTracker.Api_HostAddress = https://localhost:1338

POST {{IssueTracker.Api_HostAddress}}/catalog
Content-Type: application/json

{
  //CreateCatalogItemRequest
}

###

GET {{IssueTracker.Api_HostAddress}}/catalog/{id:guid}

###
