# For more info on HTTP files go to https://aka.ms/vs/httpfile

@apiUrl = https://localhost:1338

# Members of the Software Center can add new items to our catalog of supported software
# We have a "COLLECTION" of supported software, and we want to APPEND a new subordinate resource (DOCUMENT) 
#to that collection.

POST {{apiUrl}}/catalog
Content-Type: application/json

{
  "title": "Visual Studio",
  "description": "An integrated dev environment for all"  
}

###
GET {{apiUrl}}/catalog/9a7cc2be-a55a-4806-9d93-bbd16621d812

